# Temel imaj
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80


# Build aşaması
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Proje dosyasını kopyala ve bağımlılıkları yükle
COPY ["frontend.csproj", "./"]
RUN dotnet restore "frontend.csproj"

# Kalan dosyaları kopyala ve build et
COPY . .
RUN dotnet build "frontend.csproj" -c Release -o /app/build

# Yayın aşaması
FROM build AS publish
RUN dotnet publish "frontend.csproj" -c Release -o /app/publish

# Çalışma aşaması
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY wwwroot /frontend/wwwroot
ENTRYPOINT ["dotnet", "frontend.dll"]
